[project]
name = "seinpy"
version = "0.1.0"
description = "Seinfeld Script Database"
readme = "README.md"
authors = [
    { name = "trevorb1", email = "trevor_barnes@sfu.ca" }
]
requires-python = ">=3.13"
dependencies = [
    "kagglehub>=0.3.12",
    "polars>=1.31.0",
    "pydantic>=2.11.7",
    "requests>=2.32.4",
]

[project.scripts]
seinpy = "seinpy:main"

[project.optional-dependencies]
dev = [
    "pytest>=8.4.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
