name: Feature Request
description: Suggest an idea or enhancement for seinpy.
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem / Use Case
      description: Is your feature request related to a problem? A clear and concise description of what the problem or limitation is.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Do you have a suggestion for how to solve the problem or limitation? A clear and concise description of what you want to happen and how you envision it working.
      placeholder: Describe your proposed solution or feature...
    validations:
      required: fasle

